otu_mat<-read.table("C:/Users/Admin/Desktop/OTUB.txt", header = TRUE, row.names="Otu", sep = "\t", na.strings="NA", dec=".", strip.white=TRUE)
tax_mat<-read.table("C:/Users/Admin/Desktop/TaxonomyB.txt", header = TRUE, row.names="Otu", sep = "\t", na.strings="NA", dec=".", strip.white=TRUE)
samples_df<-read.csv("C:/Users/Admin/Desktop/sample.csv", header = TRUE, row.names="Samples", sep = ",", na.strings="NA", dec=".", strip.white=TRUE, stringsAsFactors = FALSE)
otu_mat <- as.matrix(otu_mat)
tax_mat <- as.matrix(tax_mat)
OTU = otu_table(otu_mat, taxa_are_rows = TRUE)
TAX = tax_table(tax_mat)
samples = sample_data(samples_df)
physeq = phyloseq(OTU, TAX, samples)
physeq
total = median(sample_sums(physeq))
standf = function(x, t=total) round(t * (x / sum(x)))
physeq = transform_sample_counts(physeq, standf)
plot_heatmap(physeq, method = "NMDS", distance = "bray")
physeq_abund <- filter_taxa(physeq, function(x) sum(x > total * 0.20) > 0, TRUE)